apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: furikuri/demo
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
#  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: furikuri/demo
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http